logging:
  level:
    org.springframework: info
    MOIYS.project.to_do_list_web_app: debug

spring:
  application:
    name: 04-To-Do-List-web-app

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    format:
      date: yyyy-MM-dd

  datasource:
    url: jdbc:mysql://localhost:3306/todos
    username: todos-user
    password: 1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update